
CREATE TABLE IF NOT EXISTS siswa (
    id VARCHAR(255) PRIMARY KEY,
    status VARCHAR(50),
    siswa_namaLengkap VARCHAR(255),
    siswa_nis VARCHAR(50),
    siswa_nisn VARCHAR(50),
    siswa_jenisKelamin VARCHAR(50),
    siswa_tempatLahir VARCHAR(100),
    siswa_tanggalLahir DATE,
    siswa_agama VARCHAR(50),
    siswa_kewarganegaraan VARCHAR(50),
    siswa_jumlahSaudara INT,
    siswa_bahasa VARCHAR(100),
    siswa_golonganDarah VARCHAR(5),
    siswa_telepon VARCHAR(50),
    siswa_alamatKkProvinsi VARCHAR(100),
    siswa_alamatKkKabupaten VARCHAR(100),
    siswa_alamatKkKecamatan VARCHAR(100),
    siswa_alamatKkDesa VARCHAR(100),
    siswa_domisiliProvinsi VARCHAR(100),
    siswa_domisiliKabupaten VARCHAR(100),
    siswa_domisiliKecamatan VARCHAR(100),
    siswa_domisiliDesa VARCHAR(100),
    siswa_namaAyah VARCHAR(255),
    siswa_namaIbu VARCHAR(255),
    siswa_pendidikanAyah VARCHAR(100),
    siswa_pendidikanIbu VARCHAR(100),
    siswa_pekerjaanAyah VARCHAR(100),
    siswa_pekerjaanIbu VARCHAR(100),
    siswa_namaWali VARCHAR(255),
    siswa_hubunganWali VARCHAR(100),
    siswa_pendidikanWali VARCHAR(100),
    siswa_pekerjaanWali VARCHAR(100),
    siswa_alamatOrangTua TEXT,
    siswa_teleponOrangTua VARCHAR(50),
    siswa_asalSekolah VARCHAR(255),
    siswa_nomorSttb VARCHAR(100),
    siswa_tanggalSttb DATE,
    siswa_pindahanAsalSekolah VARCHAR(255),
    siswa_pindahanDariTingkat VARCHAR(50),
    siswa_pindahanDiterimaTanggal DATE,
    siswa_lulusTahun VARCHAR(10),
    siswa_lulusNomorIjazah VARCHAR(100),
    siswa_lulusMelanjutkanKe VARCHAR(255),
    siswa_pindahKeSekolah VARCHAR(255),
    siswa_pindahTingkatKelas VARCHAR(50),
    siswa_pindahKeTingkat VARCHAR(50),
    siswa_keluarAlasan TEXT,
    siswa_keluarTanggal DATE,
    documents JSON,
    siswa_fotoProfil JSON
);

CREATE TABLE IF NOT EXISTS pegawai (
    id VARCHAR(255) PRIMARY KEY,
    status VARCHAR(50),
    pegawai_nama VARCHAR(255),
    pegawai_jenisKelamin VARCHAR(50),
    pegawai_tempatLahir VARCHAR(100),
    pegawai_tanggalLahir DATE,
    pegawai_statusPerkawinan VARCHAR(50),
    pegawai_jabatan VARCHAR(100),
    pegawai_terhitungMulaiTanggal DATE,
    pegawai_nip VARCHAR(100),
    pegawai_nuptk VARCHAR(100),
    pegawai_nrg VARCHAR(100),
    pegawai_tanggalPerkawinan DATE,
    pegawai_namaPasangan VARCHAR(255),
    pegawai_jumlahAnak INT,
    pegawai_bidangStudi VARCHAR(100),
    pegawai_tugasTambahan VARCHAR(100),
    pegawai_alamatKabupaten VARCHAR(100),
    pegawai_alamatKecamatan VARCHAR(100),
    pegawai_alamatDesa VARCHAR(100),
    pegawai_alamatDusun VARCHAR(100),
    pegawai_phaspoto JSON,
    pegawai_pendidikanSD JSON,
    pegawai_pendidikanSMP JSON,
    pegawai_pendidikanSMA JSON,
    pegawai_pendidikanDiploma JSON,
    pegawai_pendidikanS1 JSON,
    pegawai_pendidikanS2 JSON,
    pegawai_skPengangkatan JSON,
    pegawai_skNipBaru JSON,
    pegawai_skFungsional JSON,
    pegawai_beritaAcaraSumpah JSON,
    pegawai_sertifikatPendidik JSON,
    pegawai_sertifikatPelatihan JSON,
    pegawai_skp JSON,
    pegawai_karpeg JSON,
    pegawai_karisKarsu JSON,
    pegawai_bukuNikah JSON,
    pegawai_kartuKeluarga JSON,
    pegawai_ktp JSON,
    pegawai_akteKelahiran JSON,
    pegawai_kartuTaspen JSON,
    pegawai_npwp JSON,
    pegawai_kartuBpjs JSON,
    pegawai_bukuRekening JSON
);

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('superadmin', 'admin', 'user') NOT NULL,
    status ENUM('active', 'blocked') NOT NULL,
    avatar VARCHAR(255)
);

-- Note: The password here is NOT securely hashed. This is for setup convenience only.
-- In a real application, you should hash this password using a proper library like bcrypt.
INSERT INTO users (id, email, name, password, role, status, avatar) 
VALUES ('1', 'superadmin@gmail.com', 'Super Admin', 'hashed_superadmin*#', 'superadmin', 'active', NULL)
ON DUPLICATE KEY UPDATE 
    name = 'Super Admin', 
    password = 'hashed_superadmin*#',
    role = 'superadmin',
    status = 'active';

