
-- Jalankan perintah SQL ini di klien database MySQL Anda (seperti phpMyAdmin, DBeaver, dll.)
-- untuk membuat tabel yang diperlukan oleh aplikasi.

-- Pastikan Anda telah membuat database terlebih dahulu, misalnya:
-- CREATE DATABASE maudigic_eduarchive;
-- USE maudigic_eduarchive;

-- Tabel untuk Data Siswa
CREATE TABLE IF NOT EXISTS `siswa` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `status` VARCHAR(20),
  `siswa_namaLengkap` VARCHAR(255),
  `siswa_nis` VARCHAR(50),
  `siswa_nisn` VARCHAR(50),
  `siswa_jenisKelamin` VARCHAR(20),
  `siswa_tempatLahir` VARCHAR(100),
  `siswa_tanggalLahir` DATE,
  `siswa_agama` VARCHAR(50),
  `siswa_kewarganegaraan` VARCHAR(50),
  `siswa_jumlahSaudara` INT,
  `siswa_bahasa` VARCHAR(100),
  `siswa_golonganDarah` VARCHAR(5),
  `siswa_telepon` VARCHAR(20),
  `siswa_alamatKkProvinsi` VARCHAR(50),
  `siswa_alamatKkKabupaten` VARCHAR(50),
  `siswa_alamatKkKecamatan` VARCHAR(50),
  `siswa_alamatKkDesa` VARCHAR(50),
  `siswa_domisiliProvinsi` VARCHAR(50),
  `siswa_domisiliKabupaten` VARCHAR(50),
  `siswa_domisiliKecamatan` VARCHAR(50),
  `siswa_domisiliDesa` VARCHAR(50),
  `siswa_namaAyah` VARCHAR(255),
  `siswa_namaIbu` VARCHAR(255),
  `siswa_pendidikanAyah` VARCHAR(50),
  `siswa_pendidikanIbu` VARCHAR(50),
  `siswa_pekerjaanAyah` VARCHAR(100),
  `siswa_pekerjaanIbu` VARCHAR(100),
  `siswa_namaWali` VARCHAR(255),
  `siswa_hubunganWali` VARCHAR(100),
  `siswa_pendidikanWali` VARCHAR(50),
  `siswa_pekerjaanWali` VARCHAR(100),
  `siswa_alamatOrangTua` TEXT,
  `siswa_teleponOrangTua` VARCHAR(20),
  `siswa_tinggiBadan` INT,
  `siswa_beratBadan` INT,
  `siswa_penyakit` TEXT,
  `siswa_kelainanJasmani` TEXT,
  `siswa_asalSekolah` VARCHAR(255),
  `siswa_nomorSttb` VARCHAR(100),
  `siswa_tanggalSttb` DATE,
  `siswa_pindahanAsalSekolah` VARCHAR(255),
  `siswa_pindahanDariTingkat` VARCHAR(50),
  `siswa_pindahanDiterimaTanggal` DATE,
  `siswa_lulusTahun` VARCHAR(10),
  `siswa_lulusNomorIjazah` VARCHAR(100),
  `siswa_lulusMelanjutkanKe` VARCHAR(255),
  `siswa_pindahKeSekolah` VARCHAR(255),
  `siswa_pindahTingkatKelas` VARCHAR(50),
  `siswa_pindahKeTingkat` VARCHAR(50),
  `siswa_keluarAlasan` TEXT,
  `siswa_keluarTanggal` DATE,
  `siswa_fotoProfil` JSON,
  `documents` JSON
);

-- Tabel untuk Data Pegawai
CREATE TABLE IF NOT EXISTS `pegawai` (
    `id` VARCHAR(36) NOT NULL PRIMARY KEY,
    `status` VARCHAR(20),
    `pegawai_nama` VARCHAR(255),
    `pegawai_jenisKelamin` VARCHAR(20),
    `pegawai_tempatLahir` VARCHAR(100),
    `pegawai_tanggalLahir` DATE,
    `pegawai_nip` VARCHAR(50),
    `pegawai_nuptk` VARCHAR(50),
    `pegawai_nrg` VARCHAR(50),
    `pegawai_statusPerkawinan` VARCHAR(50),
    `pegawai_tanggalPerkawinan` DATE,
    `pegawai_namaPasangan` VARCHAR(255),
    `pegawai_jumlahAnak` INT,
    `pegawai_jabatan` VARCHAR(100),
    `pegawai_bidangStudi` VARCHAR(100),
    `pegawai_tugasTambahan` VARCHAR(100),
    `pegawai_terhitungMulaiTanggal` DATE,
    `pegawai_alamatDusun` VARCHAR(100),
    `pegawai_alamatDesa` VARCHAR(50),
    `pegawai_alamatKecamatan` VARCHAR(50),
    `pegawai_alamatKabupaten` VARCHAR(50),
    `pegawai_phaspoto` JSON,
    `pegawai_pendidikanSD` JSON,
    `pegawai_pendidikanSMP` JSON,
    `pegawai_pendidikanSMA` JSON,
    `pegawai_pendidikanDiploma` JSON,
    `pegawai_pendidikanS1` JSON,
    `pegawai_pendidikanS2` JSON,
    `pegawai_skPengangkatan` JSON,
    `pegawai_skNipBaru` JSON,
    `pegawai_skFungsional` JSON,
    `pegawai_beritaAcaraSumpah` JSON,
    `pegawai_sertifikatPendidik` JSON,
    `pegawai_sertifikatPelatihan` JSON,
    `pegawai_skp` JSON,
    `pegawai_karpeg` JSON,
    `pegawai_karisKarsu` JSON,
    `pegawai_bukuNikah` JSON,
    `pegawai_kartuKeluarga` JSON,
    `pegawai_ktp` JSON,
    `pegawai_akteKelahiran` JSON,
    `pegawai_kartuTaspen` JSON,
    `pegawai_npwp` JSON,
    `pegawai_kartuBpjs` JSON,
    `pegawai_bukuRekening` JSON
);
